name: Start at commit

on: push

env:
  IMAGE_VERSION: "locadora:latest"

jobs:

  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: "Job one"
        run: env
        env:
          JOB_ONE_RESULT: Test


  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - name: "Job two"
        run: env